"""User.overall_score

Revision ID: 0851ab454246
Revises: 2143dcd2f0d6
Create Date: 2024-07-02 15:59:43.013422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0851ab454246'
down_revision = '2143dcd2f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.Integer(), nullable=True))
        batch_op.alter_column('math_score',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('reading_score',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reading_score',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('math_score',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('overall_score')

    # ### end Alembic commands ###
